templates
cssTemplate
^ '
body {
	font-size: 80%;
	background-color: #FFE8FF;
}

a { 
	text-decoration: none; 
}

a:hover { 
	color: red;
	font-style: italic;
}

li.current {
	background-color: #FFCCFF;
}

div.debuggerLink {
	font-size: 125%;
	font-weight: bold;
	background-color: #FFF4FF;
}

div.indexLink {
	background-color: #FFF4FF;
}

div.state {
	border: 2px solid;
	border-color: #FFC8FF;
}

div.stack {
	border: 2px solid;
	border-color: #FFC8FF;
}

.timeStamp {
	font-size: 120%;
	font-weight: bold; 
}

.selector {
	font-weight: bold; 
}

.selected {
	background-color: #99FF66;
}

.varName {
	font-size: 120%;
	font-weight: bold; 
}

'